title: ThoMiEn
baseurl: '/thomien.de'
url: 'https://aengl.github.io'

markdown: kramdown
plugins:
  - jekyll-minifier
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - LICENSE
  - README.md
